# -*- coding: utf-8 -*-
"""fkbcase_pythonkode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jb8jRtM3GVvn8kaU2VfhKmeDE4Jg3UY
"""

import geopandas as gpd
from shapely.geometry import Polygon
import os

# 1. Sett ditt navn for mappen der resultatet skal lagres
ditt_navn = "sverrehorn"
output_mappe = ditt_navn

# 2. Sjekk om mappen finnes, og lag den hvis den ikke gjør det
if not os.path.exists(output_mappe):
    os.makedirs(output_mappe)

# 3. Last inn GeoJSON-filen din
try:
    geodataframe = gpd.read_file("geometri.geojson")
except FileNotFoundError:
    print("Feil: Fant ikke filen 'din_fil.geojson'. Sørg for at den ligger i samme mappe som dette skriptet.")
    exit()

# 4. Reprojekter dataene til UTM32N (EPSG:25832) for å jobbe med meter
try:
    geodataframe_utm = geodataframe.to_crs(epsg=25832)
    print("Dataene er nå i UTM32N.")
except Exception as e:
    print(f"Feil ved omprojisering: {e}. Sjekker kryssing i originalt format (kan gi unøyaktige avstander).")
    geodataframe_utm = geodataframe

# 5. Lag en tom liste for å lagre objekter som krysser hverandre
kryssende_objekter = []

# 6. Gå gjennom alle par av objekter i dataene
for indeks1, objekt1 in geodataframe_utm.iterrows():
    for indeks2, objekt2 in geodataframe_utm.iterrows():
        # Sjekk at vi ikke sammenligner et objekt med seg selv
        if indeks1 < indeks2:
            # Sjekk om de to objektene krysser hverandre
            if objekt1.geometry.intersects(objekt2.geometry):
                # Legg til begge objektene i listen over kryssende objekter
                kryssende_objekter.append(geodataframe.loc[indeks1]) # Bruker originalt gdf for å beholde opprinnelig CRS
                kryssende_objekter.append(geodataframe.loc[indeks2])

# 7. Fjern duplikater fra listen over kryssende objekter
unike_kryssende_objekter = gpd.GeoDataFrame(kryssende_objekter, crs=geodataframe.crs).drop_duplicates(subset=geodataframe.geometry.name)

# 8. Lagre de kryssende objektene til en ny GeoJSON-fil i din navnemappe
output_filsti = os.path.join(output_mappe, "kryssende_objekter.geojson")
unike_kryssende_objekter.to_file(output_filsti, driver="GeoJSON")

print(f"Objektene som krysser hverandre er lagret i: {output_filsti}")